---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: libcluster-roles
  namespace: production
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: libcluster-roles
  namespace: production
subjects:
- kind: ServiceAccount
  name: default
  namespace: production
roleRef:
  kind: Role
  name: libcluster-roles
  apiGroup: rbac.authorization.k8s.io
